### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by TonyStark** [art567/mt7601usta#2]
```
In function ‘memcpy’,
    inlined from ‘rt_ioctl_iwaplist’ at /home/stark/learn/mi/art567/mt7601usta/src/os/linux/../../os/linux/sta_ioctl.c:701:2:
./include/linux/string.h:305:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^
scripts/Makefile.build:316: recipe for target '/home/stark/learn/mi/art567/mt7601usta/src/os/linux/../../os/linux/sta_ioctl.o' failed

```

**Comment by art567** [comment]
@TonyStark in order to figure out and identify cause of this problem,
I only may ask you to provide more system and environment information.

Please specify all related information and have some patience while follow all steps:

- what OS distribution do you use? ([howto: determine distribution](https://www.cyberciti.biz/faq/find-linux-distribution-name-version-number/))
- your kernel version/branch (uname -a)
- exact version of compiler (gcc -v)
- specify all packages and it's versions used as dependencies to this build
- full build log

Once i have enought information to reproduce this bug, i'll probably fix and test project in your build scenario; In other cases i could provide my recommendations to avoid this error message while building driver from source.

**Comment by TonyStark** [comment]
Hi
thanks for reply
Here is some information...
```
git clone https://github.com/art567/mt7601usta
cd mt7601usta/src
make clean
make
```
Here is log while compiling >> https://paste.ofcode.org/mq2rNkpCiiRdaqvFtRV4jq
My OS:

> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.3 LTS
> Release:	16.04
> Codename:	xenial

Kernel:

> Linux ubuntu 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> gcc --version
> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by art567** [comment]
You're tried to use an outdated and officially unsupported driver package for newest kernels.

According to [README.md](https://github.com/art567/mt7601usta/blob/master/README.md) there is new [mac80211-based driver package](https://github.com/kuba-moo/mt7601u) that's approved now on [kernel.org](https://www.kernel.org/) and has wide support by GNU/Linux community.

You can issue following command to check out if your current kernel already has appropriate driver module:

```# lsmod | grep mt7601u```

I hope it's already present and you're ready to use your stick devices without additional drivers.

When you connect stick, it must be present :

```
[ 5515.098424] mt7601u 1-6:1.0: ASIC revision: 76010001  MAC revision: 76010500
[ 5515.100954] mt7601u 1-6:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[ 5515.466817] mt7601u 1-6:1.0: Warning: unsupported EEPROM version 0d
[ 5515.466876] mt7601u 1-6:1.0: EEPROM ver:0d fae:00
[ 5515.467561] mt7601u 1-6:1.0: EEPROM country region 01 (channels 1-13)
[ 5515.713155] ieee80211 phy26: Selected rate control algorithm 'minstrel_ht'
[ 5515.718977] usbcore: registered new interface driver mt7601u
```

**Comment by art567** [comment]
Remember, this is deprecated and unsupported driver by wide GNU/Linux communities, and there's no responsibility or guarantee in any form. You use this software at your own risk. 

If you don't able to use [mt7601u](https://github.com/kuba-moo/mt7601u) or it's not present in your kernel/distro, i could only suggest you to become a beta tester of [mt7601usta](https://github.com/art567/mt7601usta) driver for 4.11+ kernels.

As we state bug persist in this repo and current driver, it fortunately still works on all systems, where newest kernels is unavailable, and new kernels are partially supported too.

I believe the error you've reported is related to recent kernel API changes in kernel 4.11+

It is a good bugfix request in similar situation ([here: lwfinger/rtl8188eu/..18a5f33](https://github.com/lwfinger/rtl8188eu/commit/18a5f33b60e25bee0b4eea05bc91ba48611505c5))
I would try to fix it for newer kernels the same way, and after testing it will be released here in main branch.

Keep watching this topic for an updates, it will be so soon.

**Comment by TonyStark** [comment]
Thanks I found it :)
Already installed in 4.13 Kernel
in prebuilt driver i cant setup hostspot
Does your driver provide AP/hotspot mode?

**Comment by art567** [comment]
These drivers are split into two different variants:

1. Client: [mt7601usta](https://github.com/art567/mt7601usta) provides only wireless client network module.

2. AP: [mt7601uap](https://github.com/art567/mt7601uap) provides wireless AP network module.

**Comment by TonyStark** [comment]
OKay
but it seems i got build error in `mt7601uap` too.
https://paste.ofcode.org/Ab2YEsKjgr4a97Yvc6M4T5

**Comment by art567** [comment]
@TonyStark compilation on newest kernels is possible, testing session is started.

**Comment by TonyStark** [comment]
Thanks
It compile without any error
however it cant connect to AP i think
getting this error in `dmesg`
```
[ 3885.729125] usbcore: registered new interface driver rt2870
[ 3885.750276] ModemManager[8164]: segfault at 0 ip 0000000000431ab3 sp 00007fffb4aa2dc0 error 4 in ModemManager[400000+103000]
```
ifconfig dont show `ra0` iface
but iwconfig show `ra0` iface
I also modified `/etc/Wireless/RT2870STA/RT2870STA.dat` to connect remote AP, but same `segfault` error.
Since 4.13* have prebuilt driver, i can go with that :)

But can  you look into `mt7601uap` compilation error?
I compiled this repo https://github.com/THLIVSQAZ/MT7601U
but it crash kernel after 5-6 minute after successful connection

Thank you :)

**Comment by MestreLion** [comment]
If  28c7601 really fixes the compile error, and the driver now works in 4.13+, then I think this issue should be closed, no? Perhaps open a new issue to discuss the AP issues
